sonar-scanner \
  -Dsonar.projectKey=java-security \
  -Dsonar.projectName="Java Web App" \
  -Dsonar.projectVersion=1.0 \
  -Dsonar.sources=src/main/java \
  -Dsonar.tests=src/test/java \
  -Dsonar.java.source=17 \
  -Dsonar.java.target=17 \
  -Dsonar.java.binaries=target/classes,target/test-classes \
  -Dsonar.java.libraries=src/main/webapp/WEB-INF/lib/guava-32.1.2-jre.jar,/Users/sylvain/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.10.7/jackson-databind-2.9.10.7.jar,/Users/sylvain/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.10/jackson-annotations-2.9.10.jar,/Users/sylvain/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.10/jackson-core-2.9.10.jar,/Users/sylvain/.m2/repository/commons-beanutils/commons-beanutils/1.9.4/commons-beanutils-1.9.4.jar,/Users/sylvain/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar,/Users/sylvain/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar,/Users/sylvain/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar,/Users/sylvain/.m2/repository/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar \
  -Dsonar.host.url=http://localhost:9000
